name: WakaTime
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c627dd4563697b6b54f77d403132432c
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
